SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
BATCH_SIZE: 
  - 16 
MODEL_CHECKPOINT: # model checkpoint as path to hugging face
  - "" 
OUT_NAME: # path where to save ppls
  - '/home/LLM_Taxonomy/LexicalEntailment/data/hyperlex_pairs_ppl.pickle' 
IN_NAME: # path of pairs to estimate ppl
  - '/home/LLM_Taxonomy/LexicalEntailment/data/hyperlex_pairs.pickle' 
LOAD: # whether to load from OUT_NAME (soft start)
  - false 
USE_DEF: # whether to use definitions
  - true 
CASE: # techniqal detail, leave unchanged
  - "pred_hypernym"
